sudo: false
addons:
  firefox: "latest"
env:
  global:
  - CF_APP=[app name]
  - CF_API=[API endpoint]
  - CF_USERNAME=[user]
  - CF_ORGANIZATION=[organization]
  - CF_SPACE=[space]
before_install:
  # Start a display server where all graphical operations happens in memory
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js: 7
branches:
  only:
    - dev1
    - dev2
    - dev3
    - dev4
    - dev5
    - dev6
notifications:
  email: true
  slack: bluemix-garage-skills:TbJLoFILC1nL93wJlP2F9YMb
before_script:
  ./scripts/merge-from-known-good.sh
script:
  npm run ci
after_success:
  ./scripts/merge-to-known-good.sh
before_deploy:
  - npm run dist
  - npm prune --production
  - npm pack
  - tar -xzvf ibm-cloud-garage-method-developer-bootcamp-1.0.0.tgz
  - mv node_modules package
deploy:
  provider: bluemixcloudfoundry
  manifest: manifest-dev.yml
  username: wgpannel@us.ibm.com
  password: \(1ny\@3cCLNYABC
  organization: BMXEDU
  space: garage-bootcamp-dev
  on:
    all_branches: true

